#!/usr/bin/env bash
# this script should display Best School 10 times excpt for the 9th iteration which should display Best School and then Hi on a new line, using the while loop.
counter=0
while [ $counter -le 10 ]; do
	if [ $counter -eq 9 ]; then
		echo "Best School \n Hi"
	else
		echo "Best School"
	fi
	counter=$((counter+1))
done
