#!/usr/bin/env bash
# this script loops from 1 to 10 displaying Best School except for 4th iteration, which says bad luck, and 8th iteration, which says good luck, all using the while loop.
counter=1
while [ $counter -le 10 ]; do
	if [ $counter -eq 4 ]; then
		echo "bad luck"
	elif [ $counter -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	counter=$((counter+1))
done
