#!/usr/bin/env bash
# script displays numbers 1 through 20 with 4 9 and 17 displaying different lines of text all using the while loop and utilizing case statement.
number=1
while [ $number -le 20 ]; do
	case $number in
		4)
			echo "$number"
			echo "bad luck from China"
			;;
		9)
			echo "$number"
			echo "bad luck from Japan"
			;;
		17)
			echo "$number"
			echo "bad luck from Italy"
			;;
		*)
			echo "$number"
			;;
		esac
		number=$((number+1))
done
