#!/usr/bin/env bash
# this script utilizing the while loop should display the time for 12 hours and 59 minutes, with hours ranging from 0 to 12 and minutes from 1 to 59.
hour=0
minute=1
while [ $hour -le 12 ]; do
	while [ $minute -le 59 ]; do
		printf "%02d:%02d\n" $hour $minute
		minute=$((minute+1))
	done
	hour=$((hour+1))
done
