#!/usr/bin/env bash
# this script displays contents of current directory in list format with only part of title after dash displayed, using for loop.
for entry in *; do
	if [ -e "$entry" ] && [ ! -L "$entry" ]; then
		if [[ "$entry" == *-* ]]; then
			name=$(echo "$entry" | cut -d'-' -f2-)
			echo "$name"
		fi
	fi
done
