#!/usr/bin/env bash
# this script displays contents of current directory in list format with only part of title after dash displayed, using for loop.
for entry in *; do
	if [-e "$entry"] && [! -L "$entry"]; then
		if [[ "$entry" == *-* ]]; then
			name="${entry#*-}"
			echo "$name"
		fi
	fi
done
